DROP DATABASE IF EXISTS PRIOREASY_ESTIMA;
CREATE DATABASE PRIOREASY_ESTIMA;
USE PRIOREASY_ESTIMA;

CREATE TABLE USUARIOS (
    USU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE
);

CREATE TABLE PROJETOS (
    PRO_DATA_INICIO DATE,
    PRO_EMPRESA VARCHAR(50),
    PRO_PREVISAO_FIM DATE,
    PRO_DESCRICAO VARCHAR(255),
    PRO_NOME VARCHAR(100),
    PRO_STATUS ENUM('EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO'),
    PRO_ID INTEGER PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE COLABORADORES (
    COL_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    COL_NOME VARCHAR(100),
    COL_EMAIL VARCHAR(255),
    COL_SENHA VARCHAR(100),
    COL_EMPRESA VARCHAR(30),
    COL_CARGO ENUM('CARGO1', 'CARGO2', 'CARGO3', 'CARGO4'),
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE STAKEHOLDERS (
    STA_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    STA_CHAVE VARCHAR(30),
    STA_SENHA VARCHAR(100),
    STA_NOME VARCHAR(100),
    STA_CARGO VARCHAR(50),
    STA_EMAIL VARCHAR(255),
    FK_USUARIOS_USU_ID INTEGER,
    FK_PROJETOS_PRO_ID INTEGER
);

CREATE TABLE REQUISITOS_FUNCIONAIS (
    REQ_ESPECIFICACAO VARCHAR(1000),
    REQ_NOME VARCHAR(100),
    REQ_NUMERO_IDENTIFICADOR INTEGER,
    REQ_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    FK_PROJETOS_PRO_ID INTEGER
);

CREATE TABLE STATUS_PRIORIZACAO (
    SPA_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    SPA_PARTICIPACAO_REALIZADA BOOLEAN,
    SPA_ALERTA_EMITIDO BOOLEAN,
    FK_STAKEHOLDERS_STA_ID INTEGER
);

CREATE TABLE RESULTADOS_REQUISITOS (
    RPR_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    RPR_RESULTADO_FINAL ENUM('DEVE SER FEITO', 'PERFORMANCE', 'ATRATIVO', 'INDIFERENTE', 'QUESTIONAVEL', 'REVERSO'),
    FK_REQUISITOS_FUNCIONAIS_REQ_ID INTEGER
);

CREATE TABLE ATORES (
    ATO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ATO_NOME VARCHAR(50),
    ATO_COMPLEXIDADE ENUM('SIMPLES', 'MEDIO', 'COMPLEXO'),
    ATO_DESCRICAO VARCHAR(255),
    FK_PROJETOS_PRO_ID INTEGER
);

CREATE TABLE FATORES_TECNICOS (
    TEC_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TEC_DESCRICAO VARCHAR(50),
    TEC_PESO DOUBLE(4,2)
);

CREATE TABLE FATORES_AMBIENTAIS (
    AMB_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    AMB_DESCRICAO VARCHAR(50),
    AMB_PESO DOUBLE(4,2)
);

CREATE TABLE CASOS_DE_USO (
    CAS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CAS_NOME VARCHAR(50),
    CAS_DESCRICAO VARCHAR(255),
    CAS_COMPLEXIDADE ENUM('SIMPLES', 'MEDIO', 'COMPLEXO'),
    FK_REQUISITOS_FUNCIONAIS_REQ_ID INTEGER
);

CREATE TABLE ESTIMATIVAS_ESFORCOS (
    EST_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    EST_RESULTADO_HORAS DOUBLE(8,2),
    EST_PESO_ATORES INTEGER,
    EST_PESO_CASOS_USO INTEGER,
    EST_PESO_PONTOS_CASOS_USO INTEGER,
    EST_TFACTOR DOUBLE(6,3),
    EST_EFACTOR DOUBLE(6,3),
    EST_RESULTADO_PONTOS_CASOS_USO DOUBLE(6,3),
    FK_PROJETOS_PRO_ID INTEGER
);

CREATE TABLE CENARIOS (
    CEN_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CEN_NOME VARCHAR(50),
    CEN_DESCRICAO VARCHAR(255),
    CEN_TIPO ENUM('PRINCIPAL', 'ALTERNATIVO'),
    FK_CASOS_DE_USO_CAS_ID INTEGER
);

CREATE TABLE COLABORADORES_PROJETOS (
    FK_COLABORADORES_COL_ID INTEGER,
    FK_PROJETOS_PRO_ID INTEGER,
    COP_ADMINISTRADOR BOOLEAN,
    COP_ATIVO BOOLEAN,
    COP_ID INTEGER PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE PRIORIZACAO_STAKEHOLDERS (
    FK_STAKEHOLDERS_STA_ID INTEGER,
    FK_REQUISITOS_FUNCIONAIS_REQ_ID INTEGER,
    PRS_CLASSIFICACAO_REQUISITO ENUM('DEVE SER FEITO', 'PERFORMANCE', 'ATRATIVO', 'INDIFERENTE', 'QUESTIONAVEL', 'REVERSO'),
    PRS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRS_RESPOSTA_NEGATIVA ENUM('GOSTARIA', 'ESPERADO', 'NAO IMPORTA', 'CONVIVO COM ISSO', 'NAO GOSTARIA'),
	PRS_RESPOSTA_POSITIVA ENUM('GOSTARIA', 'ESPERADO', 'NAO IMPORTA', 'CONVIVO COM ISSO', 'NAO GOSTARIA')
);

CREATE TABLE CALCULO_TFACTOR (
    FK_FATORES_TECNICOS_TEC_ID INTEGER,
    FK_PROJETOS_PRO_ID INTEGER,
    CTF_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CTF_RESULTADO DOUBLE(4,2)
);

CREATE TABLE CALCULO_EFACTOR (
    FK_PROJETOS_PRO_ID INTEGER,
    FK_FATORES_AMBIENTAIS_AMB_ID INTEGER,
    CEF_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CEF_RESULTADO DOUBLE(4,2)
);

ALTER TABLE COLABORADORES ADD CONSTRAINT FK_COLABORADORES_2
	FOREIGN KEY (FK_USUARIOS_USU_ID)
	REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
    
ALTER TABLE STAKEHOLDERS ADD CONSTRAINT FK_STAKEHOLDERS_2
	FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
    
ALTER TABLE STAKEHOLDERS ADD CONSTRAINT FK_STAKEHOLDERS_3
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE RESTRICT;

ALTER TABLE REQUISITOS_FUNCIONAIS ADD CONSTRAINT FK_REQUISITOS_FUNCIONAIS_2
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE CASCADE;

ALTER TABLE STATUS_PRIORIZACAO ADD CONSTRAINT FK_STATUS_PRIORIZACAO_2
	FOREIGN KEY (FK_STAKEHOLDERS_STA_ID)
    REFERENCES STAKEHOLDERS (STA_ID)
    ON DELETE CASCADE;
    
ALTER TABLE RESULTADOS_REQUISITOS ADD CONSTRAINT FK_RESULTADOS_REQUISITOS_2
	FOREIGN KEY (FK_REQUISITOS_FUNCIONAIS_REQ_ID)
    REFERENCES REQUISITOS_FUNCIONAIS (REQ_ID)
    ON DELETE CASCADE;
    
ALTER TABLE ATORES ADD CONSTRAINT FK_ATORES_2
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE RESTRICT;
    
ALTER TABLE CASOS_DE_USO ADD CONSTRAINT FK_CASOS_DE_USO_2
	FOREIGN KEY (FK_REQUISITOS_FUNCIONAIS_REQ_ID)
    REFERENCES REQUISITOS_FUNCIONAIS (REQ_ID)
    ON DELETE RESTRICT;
    
ALTER TABLE ESTIMATIVAS_ESFORCOS ADD CONSTRAINT FK_ESTIMATIVAS_ESFORCOS_2
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE CASCADE;
    
ALTER TABLE CENARIOS ADD CONSTRAINT FK_CENARIOS_2
	FOREIGN KEY (FK_CASOS_DE_USO_CAS_ID)
    REFERENCES CASOS_DE_USO (CAS_ID)
    ON DELETE RESTRICT;
    
ALTER TABLE COLABORADORES_PROJETOS ADD CONSTRAINT FK_COLABORADORES_PROJETOS_2
	FOREIGN KEY (FK_COLABORADORES_COL_ID)
    REFERENCES COLABORADORES (COL_ID)
    ON DELETE RESTRICT;
    
ALTER TABLE COLABORADORES_PROJETOS ADD CONSTRAINT FK_COLABORADORES_PROJETOS_3
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE SET NULL;
    
ALTER TABLE PRIORIZACAO_STAKEHOLDERS ADD CONSTRAINT FK_PRIORIZACAO_STAKEHOLDERS_2
	FOREIGN KEY (FK_STAKEHOLDERS_STA_ID)
    REFERENCES STAKEHOLDERS (STA_ID)
    ON DELETE SET NULL;
    
ALTER TABLE PRIORIZACAO_STAKEHOLDERS ADD CONSTRAINT FK_PRIORIZACAO_STAKEHOLDERS_3
	FOREIGN KEY (FK_REQUISITOS_FUNCIONAIS_REQ_ID)
    REFERENCES REQUISITOS_FUNCIONAIS (REQ_ID)
    ON DELETE SET NULL;
    
ALTER TABLE CALCULO_TFACTOR ADD CONSTRAINT FK_CALCULO_TFACTOR_2
	FOREIGN KEY (FK_FATORES_TECNICOS_TEC_ID)
    REFERENCES FATORES_TECNICOS (TEC_ID)
    ON DELETE SET NULL;
    
ALTER TABLE CALCULO_TFACTOR ADD CONSTRAINT FK_CALCULO_TFACTOR_3
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE SET NULL;
    
ALTER TABLE CALCULO_EFACTOR ADD CONSTRAINT FK_CALCULO_EFACTOR_2
	FOREIGN KEY (FK_FATORES_AMBIENTAIS_AMB_ID)
    REFERENCES FATORES_AMBIENTAIS (AMB_ID)
    ON DELETE SET NULL;
    
ALTER TABLE CALCULO_EFACTOR ADD CONSTRAINT FK_CALCULO_EFACTOR_3
	FOREIGN KEY (FK_PROJETOS_PRO_ID)
    REFERENCES PROJETOS (PRO_ID)
    ON DELETE SET NULL;
